import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
  ],
  productSidebar: [
    {
      type: 'autogenerated',
      dirName: 'product',
    },
  ],
  architectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],
  aiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai-context',
    },
  ],
  changelogSidebar: [
    {
      type: 'autogenerated',
      dirName: 'changelog',
    },
  ],
};

export default sidebars;
